name: Windows image build

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - 
        name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/docker-ltsc2016-vs16-dotnet:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-ltsc2016-vs16-dotnet:latest
          docker logout
