name: Windows image build

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - 
        name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/docker-ltsc2016-vs16-dotnet:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-ltsc2016-vs16-dotnet:latest
          docker logout
